### ISSUE TITLE
Continuing to get TypeError: Chatbot.init() got an unexpected keyword argument 'cookie_path'

### ISSUE THREAD

**Issue by beachboy88** [gravelBridge/AutoGPT-BingAI#13]
Using memory of type:  LocalCache
Using Browser:  chrome
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\SportsFan82\Desktop\AutoGPT Related\Auto-GPT-0.3.1\Auto-GPT-0.3.1\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\SportsFan82\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SportsFan82\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\SportsFan82\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SportsFan82\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SportsFan82\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SportsFan82\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SportsFan82\Desktop\AutoGPT Related\Auto-GPT-0.3.1\Auto-GPT-0.3.1\autogpt\cli.py", line 90, in main
    run_auto_gpt(
  File "C:\Users\SportsFan82\Desktop\AutoGPT Related\Auto-GPT-0.3.1\Auto-GPT-0.3.1\autogpt\main.py", line 171, in run_auto_gpt
    system_prompt = ai_config.construct_full_prompt()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SportsFan82\Desktop\AutoGPT Related\Auto-GPT-0.3.1\Auto-GPT-0.3.1\autogpt\config\ai_config.py", line 147, in construct_full_prompt
    prompt_generator = plugin.post_prompt(prompt_generator)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\AutoGPTBingAI.zip\AutoGPTBingAI\BingAI\__init__.py", line 58, in post_prompt
  File "plugins\AutoGPTBingAI.zip\AutoGPTBingAI\BingAI\bing_ai.py", line 34, in <module>
TypeError: Chatbot.__init__() got an unexpected keyword argument 'cookie_path'

**Comment by xiahan4956** [comment]
how to fix it? I encounter the same problem too
