### ISSUE TITLE
In Auto_gpt 0.4.0,the plugin dose not work.

### ISSUE THREAD

**Issue by xiahan4956** [gravelBridge/AutoGPT-BingAI#14]
In Auto_GPT 0.4.0

I have install edgegpt == 0.3.8

but SYSTEM return :
`SYSTEM:  Command ask_genius_bing returned: Error: 'Agent' object has no attribute 'prompt'`

if I `pip install EdgeGPT --upgrade`. The programe will raise other error.
```
Exception has occurred: ImportError
cannot import name 'Chatbot' from 'EdgeGPT' (c:\Users\xiahan\Documents\BaiduSyncdisk\code\Auto-GPT\venv\lib\site-packages\EdgeGPT\__init__.py)
  File "C:\Users\xiahan\Documents\BaiduSyncdisk\code\Auto-GPT\autogpt\config\ai_config.py", line 149, in construct_full_prompt
    prompt_generator = plugin.post_prompt(prompt_generator)
  File "C:\Users\xiahan\Documents\BaiduSyncdisk\code\Auto-GPT\autogpt\main.py", line 183, in run_auto_gpt
    system_prompt = ai_config.construct_full_prompt()
  File "C:\Users\xiahan\Documents\BaiduSyncdisk\code\Auto-GPT\autogpt\cli.py", line 96, in main
    run_auto_gpt(
  File "C:\Users\xiahan\Documents\BaiduSyncdisk\code\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
ImportError: cannot import name 'Chatbot' from 'EdgeGPT' (c:\Users\xiahan\Documents\BaiduSyncdisk\code\Auto-GPT\venv\lib\site-packages\EdgeGPT\__init__.py)
```

But in AUTO_GPT 0.3.1
I use  `pip install EdgeGPT --upgrade`. It also throw 
`cannot import name 'Chatbot' from 'EdgeGPT' (c:\Users\xiahan\Documents\BaiduSyncdisk\code\Auto-GPT\venv\lib\site-packages\EdgeGPT\__init__.py)`

When I use `edgegpt==0.3.8` ,it works

**Comment by 5632515** [comment]
> 

try to add  `from .EdgeGPT import *` into __init__.py in ..../site-packages/EdgeGPT/

**Comment by IlBoni** [comment]
HI,

I have the exact same problem but also from before AutoGPT version 0.4.
If it helps, I copy the last output:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\AutoGPT\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AutoGPT\Auto-GPT\autogpt\cli.py", line 96, in main
    run_auto_gpt(
  File "C:\Users\User\AutoGPT\Auto-GPT\autogpt\main.py", line 183, in run_auto_gpt
    system_prompt = ai_config.construct_full_prompt()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AutoGPT\Auto-GPT\autogpt\config\ai_config.py", line 149, in construct_full_prompt
    prompt_generator = plugin.post_prompt(prompt_generator)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\BingAI.zip\BingAI\__init__.py", line 58, in post_prompt
  File "plugins\BingAI.zip\BingAI\bing_ai.py", line 2, in <module>
ImportError: cannot import name 'Chatbot' from 'EdgeGPT' (C:\Program Files\Python311\Lib\site-packages\EdgeGPT\__init__.py)
```

**Comment by IlBoni** [comment]
HI,

I have the exact same problem but also from before AutoGPT version 0.4.
I'm using EdgeGPT-0.10.16, I've tried to suggestion above but nothing changed.
If it helps, I copy the last output:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\AutoGPT\Auto-GPT\autogpt\__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AutoGPT\Auto-GPT\autogpt\cli.py", line 96, in main
    run_auto_gpt(
  File "C:\Users\User\AutoGPT\Auto-GPT\autogpt\main.py", line 183, in run_auto_gpt
    system_prompt = ai_config.construct_full_prompt()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AutoGPT\Auto-GPT\autogpt\config\ai_config.py", line 149, in construct_full_prompt
    prompt_generator = plugin.post_prompt(prompt_generator)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\BingAI.zip\BingAI\__init__.py", line 58, in post_prompt
  File "plugins\BingAI.zip\BingAI\bing_ai.py", line 2, in <module>
ImportError: cannot import name 'Chatbot' from 'EdgeGPT' (C:\Program Files\Python311\Lib\site-packages\EdgeGPT\__init__.py)
```

Tank you!

**Comment by beshoo** [comment]
```
 plugins_config.yaml does not exist, creating base config.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\autoGpt\Auto-GPT-0.4.6\autogpt\__main__.py", line 5, in <module>
    autogpt.app.cli.main()
  File "C:\Users\beshoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beshoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\beshoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1666, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beshoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beshoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beshoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\autoGpt\Auto-GPT-0.4.6\autogpt\app\cli.py", line 121, in main
    run_auto_gpt(
  File "D:\autoGpt\Auto-GPT-0.4.6\autogpt\app\main.py", line 70, in run_auto_gpt
    create_config(
  File "D:\autoGpt\Auto-GPT-0.4.6\autogpt\app\configurator.py", line 99, in create_config
    config.fast_llm = check_model(config.fast_llm, "fast_llm", config=config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\autoGpt\Auto-GPT-0.4.6\autogpt\app\configurator.py", line 176, in check_model
    models = api_manager.get_models(**openai_credentials)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\autoGpt\Auto-GPT-0.4.6\autogpt\llm\api_manager.py", line 107, in get_models
    all_models = openai.Model.list(**openai_credentials)["data"]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beshoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\listable_api_resource.py", line 60, in list
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\beshoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\beshoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\beshoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: Incorrect API key provided: your-ope*******-key. You can find your API key at https://platform.openai.com/account/api-keys.
```

**Comment by BigFatherJesus** [comment]
Use `pip install git+https://github.com/acheong08/EdgeGPT.git@0.3.9`
This should resolve the error by downgrading to the version of EdgeGPT the plugin was designed for
